resources:
  - name: blog
    type: git
    source:
      uri: git@github.com:mrbuk/blog.git
      branch: pipeline
      private_key: ((private_key))

  - name: gh-pages
    type: git
    source:
      uri: git@github.com:mrbuk/blog.git
      branch: gh-pages-new
      private_key: ((private_key))

jobs:
  - name: hugo
    plan:
      - get: blog
      - get: gh-pages

      - task: build
        file: blog/pipeline/tasks/build/task.yml

      - put: gh-pages
        params:
          repository: new-gh-pages
          rebase: true
